class QueensGymException(Exception): ...


class PieceException(QueensGymException): ...


class PieceDefinitionError(PieceException): ...


class InvalidPieceError(PieceException): ...


class SquareException(QueensGymException): ...


class OccupiedSquareError(SquareException): ...
