class QueensGymException(Exception): ...


class PieceException(QueensGymException): ...


class PieceDefinitionError(PieceException): ...


class InvalidPieceError(PieceException): ...


class SquareException(QueensGymException): ...


class OccupiedSquareError(SquareException): ...


class BoardException(QueensGymException): ...


class InvalidDimensionError(BoardException): ...


class UnsafePlacementError(BoardException): ...


class FactoryException(QueensGymException): ...


class GenerationError(FactoryException): ...


class NoMoreSafeSquaresError(FactoryException): ...


class EnvironmentException(QueensGymException): ...
